services:
  postgres:
    image: pgvector/pgvector:pg15
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME:-assetmanagement_db}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASS:-postgres}
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
  django:
    build: .
    image: assetmanagement_backend-django
    restart: always
    command: >
      sh -c "
      if [ \"$$DEBUG\" = \"true\" ] || [ \"$$DEBUG\" = \"1\" ]; then
        echo 'Running server in debug (Autoreload) mode...';
        exec python manage.py runserver 0.0.0.0:${HTTP_PORT:-8000};
      else
        echo 'Running server in production mode...';
        exec gunicorn assetmanagement.wsgi:application -b unix:/tmp/gunicorn.sock -w ${GUNICORN_WORKERS:-3};
      fi
      "
    environment:
      - DB_HOST=postgres
      - DB_ENGINE=${DB_ENGINE:-django.db.backends.postgresql}
      - DB_NAME=${DB_NAME:-assetmanagement_db}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASS=${DB_PASS:-postgres}
      - DB_PORT=5432
      - TZ=${TZ:-UTC}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-assetmanagement.local_settings}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME:-admin}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD:-admin123}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL:-admin@example.com}
      - DEPLOYMENT=${DEPLOYMENT:-development}
      - DEBUG=${DEBUG:-1}
      - HTTP_PORT=${HTTP_PORT:-8000}
      - SECRET_KEY=${SECRET_KEY}
      - BACKEND_URL=${BACKEND_URL:-http://localhost:9000}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1,asset-mgmt-stg.smarthyperplanes.com}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS:-http://localhost:8000,http://localhost:9000,https://asset-mgmt-stg.smarthyperplanes.com}
      - CORS_ALLOWED_ORIGIN=${CORS_ALLOWED_ORIGIN:-https://asset-mgmt-stg.smarthyperplanes.com}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost:3000,https://asset-mgmt-stg.smarthyperplanes.com}
    
    volumes:
      # there is one big issue with volumes, even after assigning /assetmanagement to appuser, because of this
      # volume mount, the permission gets overridden by root.
      - ./assetmanagement:/app
      # because of this, any changes in the assetmanagement will be automatically reflected in the app too without building it again.
      - gunicorn-socket:/tmp
      - ./assetmanagement/staticfiles:/app/staticfiles
      # this above part created the staticfiles, it saw that it used statcfiles, and there is no static files present, so it created one.
    depends_on:
      - postgres

  nginx:
    image: nginx:stable-alpine3.20
    restart: always
    environment:
      - HTTP_PORT=${HTTP_PORT:-8000}
      - DEBUG=${DEBUG:-1}
      - TZ=${TZ:-UTC}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/templates/default.conf.template
      - ./assetmanagement/staticfiles:/usr/share/nginx/html/staticfiles
      - ./assetmanagement/media:/usr/share/nginx/html/media
      - gunicorn-socket:/tmp
    ports:
      - "127.0.0.1:${HTTP_PORT:-9000}:80"
    depends_on:
      - django

  pgadmin:
    image: dpage/pgadmin4:9.11
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-root}
      PGADMIN_CONFIG_SERVER_MODE: "True"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "127.0.0.1:${PGADMIN_HTTP_PORT:-9001}:80"
    depends_on:
      - postgres

volumes:
  postgres-data-dev:
  gunicorn-socket:
  pgadmin_data:
