# Generated by Django 5.2 on 2026-07-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_image", models.ImageField(upload_to="uploads/originals/")),
                (
                    "predicted_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads/predicted/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CORRECT", "Correct"),
                            ("INCORRECT", "Incorrect"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "detected_objects",
                    models.JSONField(blank=True, default=list, null=True),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
