# Generated by Django 5.2 on 2026-07-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="asset_model",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="brand",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="coordinates",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="depreciation_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="maintenance_period",
            field=models.IntegerField(
                blank=True, help_text="Maintenance period in days", null=True
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="pruchase_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
