# Generated by Django 5.2 on 2026-07-13 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_asset_asset_model_asset_brand_asset_coordinates_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="asset",
            old_name="pruchase_price",
            new_name="purchase_price",
        ),
    ]
