# Generated by Django 5.2 on 2026-08-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_rename_pruchase_price_asset_purchase_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='detected_objects',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='brand',
            new_name='maker',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_model',
            new_name='model_no',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='purchase_price',
            new_name='price_jpy',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='depreciation_rate',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='maintenance_period',
        ),
        migrations.AddField(
            model_name='asset',
            name='conf',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='maintenance_cycle',
            field=models.IntegerField(blank=True, help_text='Maintenance cycle in days', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='next_maintenance_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
