# Generated by Django 5.2 on 2026-08-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_asset_user_alter_asset_conf_alter_asset_coordinates_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='asset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='maintenance_cycle',
            field=models.IntegerField(blank=True, help_text='Maintenance cycle in months', null=True),
        ),
    ]
