limit_req_zone $binary_remote_addr zone=limitreqsbyaddr:10m rate=10r/s;

map "${DEBUG}" $upstream_backend {
    "true"   "http://django:${HTTP_PORT}";
    "1"      "http://django:${HTTP_PORT}";
    default  "http://unix:/tmp/gunicorn.sock";
}

server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;

  # Docker's internal DNS resolver (Required when proxy_pass uses variables)
  resolver 127.0.0.11 valid=30s;

  add_header X-XSS-Protection "1; mode=block";
  add_header X-Content-Type-Options "nosniff";
  add_header X-Download-Options "noopen";
  add_header Strict-Transport-Security "max-age=5184000";
  add_header X-Frame-Options "SAMEORIGIN";
  add_header X-DNS-Prefetch-Control "off";
  add_header Referrer-Policy "no-referrer-when-downgrade";
  add_header Content-Security-Policy "default-src 'self' 'unsafe-inline' http: https: data:; object-src 'self'; base-uri 'self'; style-src  'self' 'unsafe-inline' http: https:; img-src data: *; connect-src *; script-src 'self' 'unsafe-inline' http: https: blob:; form-action 'self';  frame-ancestors 'self';" always;

  location ~ ^/(api|admin|__debug__) {
    proxy_set_header Host $host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass $upstream_backend;



    client_max_body_size    50m;
    client_body_buffer_size 128k;
    proxy_connect_timeout   190;
    proxy_send_timeout      190;
    proxy_read_timeout      190;
    proxy_buffers           32 4k;
    # limit_req zone=limitreqsbyaddr burst=10 nodelay;
  }

  # Media: images, icons, video, audio, HTC
  location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc)$ {
    expires 1M;
    access_log off;
    add_header Cache-Control "public, no-transform";
  }

  # CSS and Javascript
  location ~* \.(?:css|js)$ {
    expires 1M;
    access_log off;
    add_header Cache-Control "public, no-transform";
  }

}